import type { AnimalView } from '../shared/types.js';
import { animalColors, speciesNames, speciesPlural } from './life-art.js';
import { icon, orders } from './ui-catalog.js';

export function worldShell(): string {
  return `<main id="game" class="game-shell" aria-label="Mundo vivo de la carta">
    <canvas id="landscape" tabindex="0" aria-label="Mundo vivo, arrastra para recorrer"></canvas>
    <div id="map-loading" class="game-loading">${icon.leaf}<span>Abriendo el mundo…</span></div>
    <header class="game-top"><button id="letter-button" class="game-brand hud-surface" aria-label="La carta">${icon.leaf}<span>Una carta <em>para Isa</em><small>UN MUNDO PARA VOLVER</small></span></button><div class="game-clock hud-surface"><span class="clock-sun" aria-hidden="true">☼</span><div><strong id="world-day">Día 1</strong><span id="world-phase">Conectando</span></div><span class="clock-line"></span><span id="connection-label" class="connection-label">Conectando</span></div><nav class="game-actions hud-surface" aria-label="Opciones del mundo"><button id="chronicle-button" class="icon-button" aria-label="Crónica">${icon.book}</button><button id="sound-toggle" class="icon-button" aria-label="Sonido opcional" aria-pressed="false">${icon.sound}</button><button id="logout-button" class="icon-button logout" aria-label="Cerrar sesión">↪</button></nav></header>
    <nav class="world-navigation hud-surface" aria-label="Cuaderno del mundo">
      <button id="observe-tool" aria-pressed="false">${icon.eye}<span>Mapa</span></button>
      <button id="population-toggle" aria-label="Población" aria-expanded="false" aria-controls="population-drawer">${icon.people}<span>Vidas</span></button>
      <button id="stats-toggle" aria-label="Vida del mundo y estadísticas" aria-expanded="false" aria-controls="stats-drawer">${icon.stats}<span>Mundo</span></button>
      <button id="layer-toggle" aria-label="Capas y coordenadas" aria-expanded="false" aria-controls="layer-drawer">${icon.layers}<span>Explorar</span></button>
      <button id="intervene-toggle" aria-expanded="false" aria-controls="tool-drawer">${icon.leaf}<span>Gestos</span></button>
    </nav>
    <div class="selection-shortcuts hud-surface"><span>IR A</span><button id="focus-s" class="role-button role-s" aria-label="Encontrar a S">S</button><button id="focus-i" class="role-button role-i" aria-label="Encontrar a I">I</button><button id="inspector-toggle" aria-expanded="false" aria-controls="inspector-drawer">${icon.people}<span id="selection-label">Ficha</span></button></div>
    <aside id="population-drawer" class="game-drawer population-drawer" hidden aria-label="Población del mundo"><header><div><p class="eyebrow">CADA VIDA, UN CAMINO</p><h2><span id="population-heading">Habitantes</span> <span id="population-count">0</span></h2></div><button class="icon-button" data-close="population" aria-label="Cerrar población">×</button></header><div class="population-tabs" role="group" aria-label="Vidas del mundo"><button data-population="people" aria-pressed="true">Habitantes</button><button data-population="animals" aria-pressed="false">Fauna</button></div><label class="search-label" for="population-search"><span id="population-search-label">Buscar habitante</span><input id="population-search" type="search" placeholder="Nombre o especialidad" autocomplete="off"></label><label id="species-filter-label" class="search-label" for="species-filter" hidden>Especie<select id="species-filter"><option value="">Todas las especies</option>${Object.entries(speciesPlural).map(([key, name]) => `<option value="${key}">${name}</option>`).join('')}</select></label><div id="species-legend" class="species-legend" hidden>${Object.entries(speciesNames).map(([key, name]) => `<span><i style="background:${animalColors[key as AnimalView['species']]}" aria-hidden="true"></i>${name}</span>`).join('')}</div><div id="population-list" class="population-list"></div><p id="population-note" class="drawer-footnote">Las habilidades cambian al practicar. Puedes observar o dar una orden.</p></aside>
    <aside id="inspector-drawer" class="game-drawer inspector-drawer" hidden aria-label="Inspector de selección">
      <header><div><button id="selection-back" class="notebook-back">${icon.arrow} Todas las vidas</button><h2 id="inspector-title">Habitante</h2></div><button class="icon-button" data-close="inspector" aria-label="Cerrar inspector">×</button></header>
      <div id="person-primary" class="control-pair"><button id="follow-toggle" class="button secondary" aria-pressed="false">${icon.eye}Seguir</button><button id="direct-toggle" class="button primary" aria-pressed="false" aria-describedby="control-help">${icon.hand}Dirigir</button></div>
      <div id="inspector-tabs" class="inspector-tabs" role="tablist" aria-label="Ficha de la selección"><button id="inspector-tab-now" data-inspector-tab="now" role="tab" aria-selected="true" aria-controls="inspector-section-now">Ahora</button><button id="inspector-tab-kit" data-inspector-tab="kit" role="tab" aria-selected="false" aria-controls="inspector-section-kit" tabindex="-1">Equipo</button><button id="inspector-tab-story" data-inspector-tab="story" role="tab" aria-selected="false" aria-controls="inspector-section-story" tabindex="-1">Historia</button></div>
      <div id="inhabitant-card" tabindex="-1"></div>
      <footer id="person-controls" class="person-command-bar">
        <p id="control-help" class="control-help"></p>
        <div id="task-palette" hidden><div class="task-groups" role="group" aria-label="Tipo de tarea"><button data-task-group="sustenance" aria-pressed="true">Sustento</button><button data-task-group="work" aria-pressed="false">Trabajo</button><button data-task-group="building" aria-pressed="false">Obras</button></div><div class="order-grid">${orders.filter(order=>order.order!=='auto').map(order=>`<button data-order="${order.order}" data-order-group="${order.group}"${order.group!=='sustenance'?' hidden':''}>${order.icon}<span>${order.title}</span></button>`).join('')}</div></div>
        <div class="command-main"><button id="task-toggle" class="button primary" aria-expanded="false" aria-controls="task-palette">${icon.hand}<span id="task-label">Dar una tarea</span></button><button data-order="auto" class="button secondary">${icon.star}<span>Autonomía</span></button></div>
      </footer>
    </aside>
    <aside id="layer-drawer" class="game-drawer layer-drawer" hidden aria-label="Capas y coordenadas"><header><div><p class="eyebrow">LEER EL PAISAJE</p><h2>Observar</h2></div><button class="icon-button" data-close="layer" aria-label="Cerrar capas">×</button></header><label for="observation-layer">Capa del mapa<select id="observation-layer"><option value="none">El paisaje</option><option value="moisture">La humedad</option><option value="food">El alimento</option></select></label><p id="layer-explanation" class="drawer-note">Agua, recursos y encuentros cambian las posibilidades.</p><label for="person-select">Ir a un habitante<select id="person-select"></select></label><label for="place-select">Ir a un lugar conocido<select id="place-select"></select></label><form id="tile-form"><fieldset><legend>Recorrer por coordenadas</legend><label for="tile-x">X<input id="tile-x" type="number" min="-9999900" max="9999900" value="0" required></label><label for="tile-y">Y<input id="tile-y" type="number" min="-9999900" max="9999900" value="0" required></label><button class="button primary" type="submit">Ir ${icon.arrow}</button></fieldset></form></aside>
    <aside id="tool-drawer" class="game-drawer tool-drawer" hidden aria-label="Gesto en el mundo"><header><div><p class="eyebrow">CAMBIAR UNA POSIBILIDAD</p><h2 id="gesture-title">Sembrar</h2></div><button class="icon-button" data-close="tool" aria-label="Cerrar gesto">×</button></header><div class="gesture-choices" role="group" aria-label="Gestos disponibles"><button data-gesture="plant" aria-pressed="true">${icon.leaf}Sembrar</button><button data-gesture="invite" aria-pressed="false">${icon.star}Invitar</button><button data-gesture="remember" aria-pressed="false">${icon.book}Recordar</button></div><p id="gesture-description" class="drawer-note"></p><div id="memory-choice" hidden><label for="memory-select">Recuerdo disponible<select id="memory-select"></select></label><p id="memory-preview" class="memory-preview"></p></div><p class="target-line">Destino: <strong id="gesture-target">toca una casilla</strong></p><button id="gesture-send" class="button primary" disabled>Sembrar aquí ${icon.arrow}</button></aside>
    <aside id="stats-drawer" class="game-drawer stats-drawer" hidden aria-label="Vida del mundo y estadísticas"><header><div><p class="eyebrow">LO QUE ESTÁ TOMANDO FORMA</p><h2>Vida del mundo</h2></div><button class="icon-button" data-close="stats" aria-label="Cerrar estadísticas">×</button></header><div class="stats-tabs" role="tablist" aria-label="Vistas de estadísticas"><button id="stats-tab-life" role="tab" data-stats="life" aria-selected="true" aria-controls="stats-content">Vida</button><button id="stats-tab-land" role="tab" data-stats="land" aria-selected="false" aria-controls="stats-content" tabindex="-1">Paisaje</button><button id="stats-tab-communities" role="tab" data-stats="communities" aria-selected="false" aria-controls="stats-content" tabindex="-1">Comunidades</button><button id="stats-tab-technology" role="tab" data-stats="technology" aria-selected="false" aria-controls="stats-content" tabindex="-1">Oficios</button><button id="stats-tab-performance" role="tab" data-stats="performance" aria-selected="false" aria-controls="stats-content" tabindex="-1">Rendimiento</button></div><div id="stats-content" role="tabpanel" aria-labelledby="stats-tab-life" tabindex="0"><p class="drawer-note">Esperando las medidas del servidor.</p></div></aside>
    <section id="return-card" class="return-toast hud-surface" hidden aria-label="Desde tu última visita"></section>
    <div class="game-message-stack"><div id="connection-notice" class="game-notice" role="status">Conectando con el mundo…</div><p id="gesture-result" class="game-result" role="status" aria-live="polite" hidden></p><p id="mode-indicator" class="mode-indicator" hidden></p></div>
    <div class="camera-controls hud-surface" aria-label="Cámara"><button id="zoom-in" class="icon-button" aria-label="Acercar mapa">+</button><button id="zoom-out" class="icon-button" aria-label="Alejar mapa">−</button><button id="map-reset" class="icon-button" aria-label="Volver a S">${icon.focus}</button></div>
    <div class="world-coordinates hud-surface"><span id="camera-coordinates">0, 0</span><span id="world-extent">Recibiendo el mundo</span></div>
    <p class="map-hint" id="map-help">Arrastra para recorrer · toca para descubrir · rueda para acercar</p>
  </main>
  <dialog id="letter-dialog" class="letter-dialog" aria-labelledby="letter-title"><button class="dialog-close icon-button" aria-label="Cerrar la carta">×</button><span class="letter-index">01 / LA CARTA</span><div class="letter-flower">${icon.leaf}</div><p class="eyebrow">BORRADOR DE APERTURA · PENDIENTE DE STEVEN</p><h2 id="letter-title">Para ti, <em>Isa.</em></h2><blockquote>Te hice un mundo pequeño. Dejé en él algo de nuestra historia y espacio para lo que todavía no sabemos.</blockquote><p class="letter-note">La voz del autor y los recuerdos reales están pendientes de revisión. S e I son representaciones provisionales; los recuerdos de prueba están identificados.</p><p class="letter-signature">Hay espacio para tomar tu propio camino.</p><button id="enter-landscape" class="button primary">Entrar al mundo ${icon.arrow}</button></dialog>
  <dialog id="chronicle-dialog" class="chronicle-dialog" aria-labelledby="journal-title"><button class="dialog-close icon-button" aria-label="Cerrar crónica">×</button><p class="eyebrow">LAS HUELLAS QUE VAN QUEDANDO</p><h2 id="journal-title">Una pequeña <em>crónica.</em></h2><p class="journal-intro">Hechos guardados por el mundo. Cada episodio conserva su causa y su origen.</p><div id="journal-events"></div></dialog>`;
}
